namespace NetAth.Model
{
    public class AuthenticatedResponse
    {
        // a jwt token has Header => contains information like the type of token eg, JWT and the algorithm eg, HS256
        // Payload => contains attribute about the logged in user
        // Signature => digital signature that gets generated by combining  the header and the payload
        public string? Token { get; set; }
        public string? RefreshToken { get; set; }
    }
}
